import java.util.ArrayList;

public class MerkleThread implements Runnable {
    public static volatile ArrayList<String> lstWords;
    private int iMerkleTreeInputs = 4;

    public run() {
        Util objUtil = new Util();
        lstWords = new ArrayList<>();

        while (true) {
            objUtil.sleepRandomTime();
            String sNewWord = MerkleManager.grabWord();
            if (sNewWord != null) {
                System.out.println("Merkle grabbed a new word");
                lstWords.add(sNewWord);
                if (lstWords.size() == iMerkleTreeInputs) {
                    // TODO: set MerkleManager.sMerkleRoot to the merkle root generated by the getMerkleRoot method on util class.
                }
            }
        }
    }
}
